services:
  app:
    container_name: conectar-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    ports:
      - 3000:3333
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - conectar-network

  db:
    image: postgres:16-alpine
    container_name: conectar-postgres
    environment:
      POSTGRES_DB: conectar-company
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - conectar-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: conectar-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: erick.marllon@outlook.com.br
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    ports:
      - 18080:80
    volumes:
      - pgadmin_data:/root/.pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - conectar-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  conectar-network:
    driver: bridge
