import { LoggerModule } from '@/infrastructure/gateways/logger/logger.module';
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TypeOrmConfigModule } from './typeorm-config.module';

// ENTITIES
import {
  PgsqlAddressM,
  PgsqlCategoryM,
  PgsqlEventTypeM,
  PgsqlGatewaySettingM,
  PgsqlGoogleCalendarM,
  PgsqlInvoiceM,
  PgsqlLog,
  PgsqlMediaM,
  PgsqlNotificationEventM,
  PgsqlOrderItemM,
  PgsqlOrderM,
  PgsqlPaymentM,
  PgsqlPermissionM,
  PgsqlPlanM,
  PgsqlProductM,
  PgsqlProductReviewM,
  PgsqlRoleM,
  PgsqlRolePermissionM,
  PgsqlServiceM,
  PgsqlServiceScheduleM,
  PgsqlSessionM,
  PgsqlTenantAddressM,
  PgsqlTenantM,
  PgsqlTenantNotificationSettingM,
  PgsqlTenantSocialM,
  PgsqlTenantSubscriptionM,
  PgsqlUserM,
  PgsqlUserPermissionM,
  PgsqlUserSocialM,
} from './entities';

// REPOSITORIES
import {
  MediaRepository,
  PgsqlAddressRepository,
  PgsqlCategoryRepository,
  PgsqlEventTypeMRepository,
  PgsqlGatewaySettingRepository,
  PgsqlGoogleCalendarRepository,
  PgsqlInvoiceRepository,
  PgsqlLogRepository,
  PgsqlNotificationEventRepository,
  PgsqlOrderItemRepository,
  PgsqlOrderRepository,
  PgsqlPaymentRepository,
  PgsqlPermissionRepository,
  PgsqlPlanRepository,
  PgsqlProductRepository,
  PgsqlProductReviewRepository,
  PgsqlRolePermissionPermissionRepository,
  PgsqlRoleRepository,
  PgsqlServiceRepository,
  PgsqlServiceScheduleRepository,
  PgsqlSessionRepository,
  PgsqlTenantAddressRepository,
  PgsqlTenantNotificationSettingRepository,
  PgsqlTenantRepository,
  PgsqlTenantSocialRepository,
  PgsqlTenantSubscriptionRepository,
  PgsqlUserPermissionRepository,
  PgsqlUserRepository,
  PgsqlUserSocialRepository,
  RawRepository,
} from './repositories';

@Module({
  imports: [
    TypeOrmConfigModule,
    TypeOrmModule.forFeature([
      PgsqlAddressM,
      PgsqlCategoryM,
      PgsqlEventTypeM,
      PgsqlGatewaySettingM,
      PgsqlGoogleCalendarM,
      PgsqlMediaM,
      PgsqlNotificationEventM,
      PgsqlOrderItemM,
      PgsqlOrderM,
      PgsqlPermissionM,
      PgsqlInvoiceM,
      PgsqlLog,
      PgsqlPaymentM,
      PgsqlPlanM,
      PgsqlProductM,
      PgsqlRoleM,
      PgsqlSessionM,
      PgsqlTenantM,
      PgsqlTenantSubscriptionM,
      PgsqlUserM,
      PgsqlProductReviewM,
      PgsqlProductM,
      PgsqlRolePermissionM,
      PgsqlServiceScheduleM,
      PgsqlServiceM,
      PgsqlTenantAddressM,
      PgsqlTenantNotificationSettingM,
      PgsqlTenantSocialM,
      PgsqlUserPermissionM,
      PgsqlUserSocialM,
    ]),
    LoggerModule,
  ],
  providers: [
    PgsqlAddressRepository,
    PgsqlCategoryRepository,
    PgsqlEventTypeMRepository,
    PgsqlGatewaySettingRepository,
    PgsqlGoogleCalendarRepository,
    PgsqlInvoiceRepository,
    PgsqlLogRepository,
    MediaRepository,
    PgsqlNotificationEventRepository,
    PgsqlOrderItemRepository,
    PgsqlOrderRepository,
    PgsqlPaymentRepository,
    PgsqlProductReviewRepository,
    PgsqlPermissionRepository,
    PgsqlPermissionRepository,
    PgsqlPlanRepository,
    PgsqlProductRepository,
    RawRepository,
    PgsqlRolePermissionPermissionRepository,
    PgsqlRoleRepository,
    PgsqlServiceScheduleRepository,
    PgsqlServiceRepository,
    PgsqlSessionRepository,
    PgsqlTenantAddressRepository,
    PgsqlTenantNotificationSettingRepository,
    PgsqlTenantSocialRepository,
    PgsqlTenantSubscriptionRepository,
    PgsqlTenantRepository,
    PgsqlUserPermissionRepository,
    PgsqlUserSocialRepository,
    PgsqlUserRepository,
  ],
  exports: [
    PgsqlAddressRepository,
    PgsqlCategoryRepository,
    PgsqlEventTypeMRepository,
    PgsqlGatewaySettingRepository,
    PgsqlGoogleCalendarRepository,
    PgsqlInvoiceRepository,
    PgsqlLogRepository,
    MediaRepository,
    PgsqlNotificationEventRepository,
    PgsqlOrderItemRepository,
    PgsqlOrderRepository,
    PgsqlPaymentRepository,
    PgsqlProductReviewRepository,
    PgsqlPermissionRepository,
    PgsqlPermissionRepository,
    PgsqlPlanRepository,
    PgsqlProductRepository,
    RawRepository,
    PgsqlRolePermissionPermissionRepository,
    PgsqlRoleRepository,
    PgsqlServiceScheduleRepository,
    PgsqlServiceRepository,
    PgsqlSessionRepository,
    PgsqlTenantAddressRepository,
    PgsqlTenantNotificationSettingRepository,
    PgsqlTenantSocialRepository,
    PgsqlTenantSubscriptionRepository,
    PgsqlTenantRepository,
    PgsqlUserPermissionRepository,
    PgsqlUserSocialRepository,
    PgsqlUserRepository,
  ],
})
export class PgsqlModule {}
